/**
 * Curated set of lucide icons used as board glyphs. The DB stores the icon
 * *name* (a key of this registry); we resolve it to a component at render
 * time, falling back to Lightbulb for anything unknown.
 */
import {
  Lightbulb,
  Rocket,
  Film,
  Clapperboard,
  Tv,
  Music,
  Headphones,
  Mic,
  Camera,
  BookOpen,
  Book,
  GraduationCap,
  Brain,
  Compass,
  Map,
  MapPin,
  Plane,
  Globe,
  Mountain,
  Bike,
  Car,
  Utensils,
  Coffee,
  Wine,
  Dumbbell,
  Heart,
  Leaf,
  Palette,
  PenTool,
  Code,
  Wrench,
  FlaskConical,
  Briefcase,
  Wallet,
  ShoppingCart,
  Gift,
  Home,
  Star,
  Sparkles,
  Trophy,
  Target,
  Flag,
  Gamepad2,
  Dog,
  type LucideIcon,
} from "lucide-react";

export const IDEA_ICONS: Record<string, LucideIcon> = {
  Lightbulb,
  Rocket,
  Film,
  Clapperboard,
  Tv,
  Music,
  Headphones,
  Mic,
  Camera,
  BookOpen,
  Book,
  GraduationCap,
  Brain,
  Compass,
  Map,
  MapPin,
  Plane,
  Globe,
  Mountain,
  Bike,
  Car,
  Utensils,
  Coffee,
  Wine,
  Dumbbell,
  Heart,
  Leaf,
  Palette,
  PenTool,
  Code,
  Wrench,
  FlaskConical,
  Briefcase,
  Wallet,
  ShoppingCart,
  Gift,
  Home,
  Star,
  Sparkles,
  Trophy,
  Target,
  Flag,
  Gamepad2,
  Dog,
};

/** Ordered list of icon names for the picker grid. */
export const IDEA_ICON_NAMES = Object.keys(IDEA_ICONS);

export const DEFAULT_ICON = "Lightbulb";

/** Resolve an icon name to its component (Lightbulb fallback). */
export function getIdeaIcon(name: string | undefined | null): LucideIcon {
  return (name && IDEA_ICONS[name]) || Lightbulb;
}
